--- 
- name: Deploy my-cni-demo using ansible 
  hosts: all 
  vars_files: 
  - vars.yaml

  tasks: 
    - name: allow communication across hosts for bridge cni0
      command: |
          ip route add {{ item.podcidr[0] }} via {{ item.ip }} dev {{ interface }} 
      ignore_errors: yes 
      when: ansible_hostname != item.name
      loop: "{{ nodeinfo }}"

    - name: allow communication across hosts for bridge cni1
      command: |
          ip route add {{ item.podcidr[1] }} via {{ item.ip }} dev {{ interface }} 
      ignore_errors: yes 
      when: ansible_hostname != item.name
      loop: "{{ nodeinfo }}"

    - name: allow communication across hosts for bridge cni2
      command: |
          ip route add {{ item.podcidr[2] }} via {{ item.ip }} dev {{ interface }} 
      ignore_errors: yes 
      when: ansible_hostname != item.name
      loop: "{{ nodeinfo }}"

    - name: ensure that /etc/cni/net.d exists 
      file: 
        state: directory 
        recurse: yes 
        path: /etc/cni/net.d 

    - name: deploy configuration file 
      template: 
        src: conf/10-multi-bridge-cni.conf.j2 
        dest: /etc/cni/net.d/10-multi-bridge-cni.conf 
        owner: root
        group: root
        mode: 0644

    - name: deploy binary file 
      copy:
        src: bin/multi-bridge
        dest: /opt/cni/bin/multi-bridge
        owner: root
        group: root
        mode: 0755

