---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: netshoot
  name: netshoot1
  annotations: 
    multi-bridge.cni.kubernetes.io/dev: "net1,net2"
spec:
  containers:
  - image: nicolaka/netshoot
    name: netshoot 
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10;done"]
  nodeSelector: 
    kubernetes.io/hostname: cni-master01
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: netshoot
  name: netshoot2
  annotations: 
    multi-bridge.cni.kubernetes.io/dev: "net1"
spec:
  containers:
  - image: nicolaka/netshoot
    name: netshoot 
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10;done"]
  nodeSelector: 
    kubernetes.io/hostname: cni-worker01
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: netshoot
  name: netshoot3
  annotations: 
    multi-bridge.cni.kubernetes.io/dev: "net2"
spec:
  containers:
  - image: nicolaka/netshoot
    name: netshoot 
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10;done"]
  nodeSelector: 
    kubernetes.io/hostname: cni-worker02
